services:
  # ---------------------------------------------
  # FRONTEND: Vue 3 + Tailwind
  # ---------------------------------------------
  frontend:
    build:
      context: ../../frontend-code
      dockerfile: ../infrastructure/docker/frontend-dev/dockerfile
    container_name: frontend-lostfinder
    ports:
      - "5173:5173"
    volumes:
    - ../../frontend-code:/app          
    - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true 
    networks:
      - dev-network
    depends_on:
      - backend

  # ---------------------------------------------
  # BACKEND: Python API (DDD)
  # ---------------------------------------------
  backend:
    build:
      context: ../../backend-code
      dockerfile: ../infrastructure/docker/backend-dev/dockerfile
    container_name: backend-lostfinder
    ports:
      - "5000:5000"
    volumes:
      - ../../backend-code:/app
    environment:
      - DATABASE_URL=postgresql://findit_user:findit_pass@db:5432/findit_db
      - FLASK_APP=app.py
    networks:
      - dev-network
    depends_on:
      - db

  # ---------------------------------------------
  # BANCO DE DADOS: PostgreSQL
  # ---------------------------------------------
  db:
    image: postgres:15-alpine
    container_name: database-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: findit_user
      POSTGRES_PASSWORD: findit_pass
      POSTGRES_DB: findit_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev-network

  # ---------------------------------------------
  # STACK OBSERVABILIDADE: loki, grafana e prometheus
  # ---------------------------------------------

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - dev-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - dev-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
      - prometheus
    networks:
      - dev-network

volumes:
  postgres_data:

networks:
  dev-network:
    driver: bridge
